name: Package-and-Upload

# Pyinstaller requires that executables for each OS are built on that OS
# This action is intended to build on each of the supported OS's: mac (x86 and arm), windows, linux.
# and then upload all four files to a new release

# reference material:
# https://data-dive.com/multi-os-deployment-in-cloud-using-pyinstaller-and-github-actions
# https://anshumanfauzdar.medium.com/using-github-actions-to-bundle-python-application-into-a-single-package-and-automatic-release-834bd42e0670

on:
  push:
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  buildexe:
    name: Build executables and upload them to the existing release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            TARGET: ubuntu
            CONTAINER: quay.io/centos/centos:stream9
            CMD_BUILD: >
              pyinstaller --clean -y --distpath ./dist/ubuntu tabcmd-linux.spec &&
              chown -R --reference=. ./dist/ubuntu
            OUT_FILE_NAME: tabcmd
            UPLOAD_FILE_NAME: tabcmd

    container:
      image: ${{ matrix.CONTAINER }}
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies and build
        run: |
          whereis python
          python --version
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          pip install .
          pip install .[package]
          doit version
          python -m build

      - name: Package with pyinstaller for ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD}}

      - name: Verify GLIBC compatibility
        if: matrix.TARGET == 'ubuntu'
        run: |
          cat /etc/os-release
          ldd ./dist/ubuntu/tabcmd | grep libc
          # Should show GLIBC version 2.28 or lower

      - name: Validate package for ${{matrix.TARGET}}
        if: matrix.TARGET != 'macos'
        run: ./dist/${{ matrix.TARGET }}/${{matrix.OUT_FILE_NAME}}

      - name: Validate package for Mac
        if: matrix.TARGET == 'macos'
        run: ./dist/${{ matrix.TARGET }}/${{ matrix.OUT_FILE_NAME }}/Contents/MacOS/${{ matrix.APP_BINARY_FILE_NAME }}

      - name: Tar app bundle for Mac
        if: matrix.TARGET == 'macos'
        run: |
          rm -f dist/${{ matrix.TARGET }}/${{ matrix.APP_BINARY_FILE_NAME }}
          cd dist/${{ matrix.TARGET }}
          tar -cvf ${{ matrix.UPLOAD_FILE_NAME }} ${{ matrix.OUT_FILE_NAME }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.TARGET }}
          path: dist
